### ISSUE TITLE
Homebrew installation

### ISSUE THREAD

**Issue by jaxxstorm** [harrybrwn/apizza#3]
Would be great to be able to install this from homebrew, goreleaser would help here!

**Comment by harrybrwn** [comment]
Nice, I've been looking for a release tool that fits in with my CI workflow and I haven't heard of goreleaser I'll check it out. I've just started thinking about how I'm going to do releases but I'm planning on creating a debian package so I will figure out how to set it up for homebrew as well.

**Comment by jaxxstorm** [comment]
I'm happy to help/send a PR for goreleaser support, it should be able to take care of the debian package too.

**Comment by harrybrwn** [comment]
That would be awesome, thanks.

**Comment by whalehub** [comment]
@jaxxstorm I'm not sure if you still plan on adding goreleaser support, but I added support for apizza to [ginstall.sh](https://github.com/whalehub/ginstall.sh) today in case you're looking for an alternative way to install/update this tool in the meantime.

**Comment by harrybrwn** [comment]
Ok, so I added support for homebrew installation and might add snap if people want it.
